[tool.poetry]
name = "ucsdx-algs204x"
version = "0.1.0"
description = ""
authors = ["Sumit Haswar <sumithaswar@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
